<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { useMetronome } from './composables/useMetronome'
import logoUrl from './assets/logo-sheet.svg'

const {
  tempo,
  isPlaying,
  flashId,
  flashStrong,
  timeSignature,
  muteBarsEnabled,
  barsOn,
  barsOff,
  toggle,
  setTempo,
  cycleTimeSignature,
  setBarsOn,
  setBarsOff,
} = useMetronome(120)

const TEMPO_MIN = 60
const TEMPO_MAX = 200

const sliderValue = computed({
  get: () => Math.round(tempo.value / 5) * 5,
  set: (val: number) => setTempo(val),
})

// Drives the track's filled portion; a custom-styled range input loses the
// platform's built-in progress fill, so we paint it with a gradient stop.
const sliderFill = computed(() => {
  const clamped = Math.min(TEMPO_MAX, Math.max(TEMPO_MIN, tempo.value))
  return `${((clamped - TEMPO_MIN) / (TEMPO_MAX - TEMPO_MIN)) * 100}%`
})

// Retrigger the flash animation on every pulse beat, even if flashStrong
// is unchanged from last time, by toggling the class off and back on
// after a forced reflow.
const flashing = ref(false)
let flashTimeoutId: number | undefined

watch(flashId, () => {
  flashing.value = false
  clearTimeout(flashTimeoutId)
  requestAnimationFrame(() => {
    flashing.value = true
  })
  flashTimeoutId = window.setTimeout(() => {
    flashing.value = false
  }, 300)
})
</script>

<template>
  <div class="app">
    <header class="topbar">
      <div class="brand">
        <!-- Generated by `npm run icons` from the grid in scripts/gen-icons.ts.
             Sized by height with width auto; keep the height an even multiple of
             the grid's 16 rows or the pixel rows land on half-pixels. -->
        <span class="logo" :style="{ backgroundImage: `url(${logoUrl})` }" aria-hidden="true" />
        <h1 class="wordmark">Metro<span>Gnome</span></h1>
      </div>

      <div
        class="signal-light"
        :class="{ flashing, strong: flashStrong }"
      ></div>
    </header>

    <button class="time-sig" @click="cycleTimeSignature" aria-label="Change time signature">
      {{ timeSignature }}
    </button>

    <div class="tempo-controls">
      <button class="step-button" @click="setTempo(tempo - 1)" aria-label="Decrease by 1 BPM"><svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M6 12h12" /></svg></button>
      <div class="tempo-display">
        <span class="tempo-value">{{ tempo }}</span>
        <span class="unit">BPM</span>
      </div>
      <button class="step-button" @click="setTempo(tempo + 1)" aria-label="Increase by 1 BPM"><svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M12 6v12M6 12h12" /></svg></button>
    </div>

    <div class="slider-row">
      <span class="slider-bound">{{ TEMPO_MIN }}</span>
      <input
        class="slider"
        type="range"
        :min="TEMPO_MIN"
        :max="TEMPO_MAX"
        step="5"
        aria-label="Tempo"
        :style="{ '--fill': sliderFill }"
        v-model.number="sliderValue"
      />
      <span class="slider-bound">{{ TEMPO_MAX }}</span>
    </div>

    <div class="mute-bars">
      <label class="mute-toggle">
        <span>Mute Bars</span>
        <span class="switch" :class="{ on: muteBarsEnabled }">
          <input type="checkbox" v-model="muteBarsEnabled" />
          <span class="switch-thumb"></span>
        </span>
      </label>

      <div v-if="muteBarsEnabled" class="mute-steppers">
        <div class="mute-stepper">
          <span class="mute-stepper-label">Play</span>
          <div class="mute-stepper-controls">
            <button class="mini-button" @click="setBarsOn(barsOn - 1)" aria-label="Fewer bars on"><svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M6 12h12" /></svg></button>
            <span class="mute-stepper-value">{{ barsOn }}</span>
            <button class="mini-button" @click="setBarsOn(barsOn + 1)" aria-label="More bars on"><svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M12 6v12M6 12h12" /></svg></button>
          </div>
        </div>
        <div class="mute-stepper">
          <span class="mute-stepper-label">Mute</span>
          <div class="mute-stepper-controls">
            <button class="mini-button" @click="setBarsOff(barsOff - 1)" aria-label="Fewer bars off"><svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M6 12h12" /></svg></button>
            <span class="mute-stepper-value">{{ barsOff }}</span>
            <button class="mini-button" @click="setBarsOff(barsOff + 1)" aria-label="More bars off"><svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M12 6v12M6 12h12" /></svg></button>
          </div>
        </div>
      </div>
    </div>

    <button class="play-button" :class="{ playing: isPlaying }" @click="toggle">
      {{ isPlaying ? 'Stop' : 'Start' }}
    </button>
  </div>
</template>

<style scoped>
.app {
  --bg: #12141a;
  --surface: #1a1d25;
  --surface-raised: #23262f;
  --surface-pressed: #2f333e;
  --border: #2a2e3a;
  /* Channel triplets, so a solid colour and its translucent variants are one
     source and can't drift apart. --accent-rgb is the gnome's hat blue —
     PAL.B in scripts/gen-icons.ts; change it there and here together. */
  --accent-rgb: 58, 123, 253;
  --warm-rgb: 255, 157, 61;
  /* PAL.R — the bobble on the gnome's hat. */
  --stop-rgb: 255, 68, 51;

  --accent: rgb(var(--accent-rgb));
  --accent-glow: rgba(var(--accent-rgb), 0.28);
  /* Deliberately lighter than --accent: a focus ring has to read against the
     accent-coloured surfaces it lands on. */
  --accent-strong: #5590ff;
  --warm: rgb(var(--warm-rgb));
  --warm-fill: rgba(var(--warm-rgb), 0.12);
  --warm-press: rgba(var(--warm-rgb), 0.22);
  --stop: rgb(var(--stop-rgb));
  --stop-glow: rgba(var(--stop-rgb), 0.28);
  /* Beat indicator at rest — neutral, since the pulses are blue and white. */
  --signal-off: #22252e;
  --text: #eef0f5;
  --text-muted: #9aa2b5;
  --text-faint: #6b7385;
  /* Inset hairlines that mark a surface as pressable.
     The coloured rings are opaque on purpose. Alpha composites toward whatever
     is behind it, so a translucent accent over the dark button surface loses
     most of its blue channel and lands on a muddy grey — 45% blue over
     --surface-raised renders rgb(45,76,140), not the accent at all. Only a
     solid colour reproduces the hat blue exactly. --ring stays translucent
     because it is meant to read as a neutral highlight, not as a hue. */
  --ring: inset 0 0 0 1px rgba(255, 255, 255, 0.08);
  --ring-accent: inset 0 0 0 1px var(--accent);
  --ring-warm: inset 0 0 0 1px var(--warm);
  --ring-on-fill: inset 0 0 0 1px rgba(255, 255, 255, 0.72);

  position: relative;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: 2rem;
  height: 100vh;
  height: 100dvh;
  padding: 2rem;
  padding-top: max(5.5rem, calc(env(safe-area-inset-top) + 3.5rem));
  padding-bottom: max(2rem, env(safe-area-inset-bottom));
  padding-left: max(2rem, env(safe-area-inset-left));
  padding-right: max(2rem, env(safe-area-inset-right));
  background: var(--bg);
  color: var(--text);
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
}

.topbar {
  position: absolute;
  top: max(1rem, env(safe-area-inset-top));
  left: max(1.25rem, env(safe-area-inset-left));
  right: max(1.25rem, env(safe-area-inset-right));
  display: flex;
  align-items: center;
  justify-content: center;
  /* Scale driver for the whole header. It lives here rather than on .brand so
     the signal light can offset itself in the same em basis. */
  font-size: clamp(1.6rem, calc(14.6vw - 20.3px), 2.75rem);
}

/* One scale driver for the whole lockup: the logo and gap are sized in em, so
   they track the wordmark instead of being pinned while it shrinks.
   Baseline rather than centre — for a replaced element the baseline is its
   bottom edge, so the gnome sits down on the wordmark's baseline instead of
   hanging below it. */
.brand {
  display: flex;
  align-items: baseline;
  gap: 0.22em;
}

/* A background-image sprite rather than an <img>, so the blink is a
   background-position step instead of a second element to cross-fade. An empty
   inline-block takes its baseline from its bottom margin edge — the same rule a
   replaced element follows — so .brand's baseline alignment is unchanged. */
.logo {
  --logo-frames: 2;
  display: inline-block;
  height: 0.98em;
  /* The source grid is 12x16; keep the aspect ratio explicit because there's no
     intrinsic size to fall back on now. */
  width: calc(0.98em * 12 / 16);
  flex-shrink: 0;
  background-repeat: no-repeat;
  /* One frame fills the box; the sheet overflows to the right by the rest. */
  background-size: calc(var(--logo-frames) * 100%) 100%;
  background-position-x: 0%;
  /* Nearest-neighbour: this is pixel art, and the SVG is drawn at 12px wide. */
  image-rendering: pixelated;
  animation: blink 7.4s step-end infinite;
}

/* Percentage background-position maps 0%..100% onto the first..last frame, so
   with 2 frames it's simply 0% open, 100% shut. Two shuts in quick succession —
   a single isolated blink reads as a glitch, a double reads as alive. */
@keyframes blink {
  0%,
  91.9% {
    background-position-x: 0%;
  }
  92% {
    background-position-x: 100%;
  }
  93.4% {
    background-position-x: 0%;
  }
  95.2% {
    background-position-x: 100%;
  }
  96.6%,
  100% {
    background-position-x: 0%;
  }
}

/* Scales with the viewport because the binding constraint is width, not
   height: "MetroGnome" is 10 characters, so the size that would make the cap
   height equal the logo's would overflow a narrow phone. */
.wordmark {
  margin: 0;
  /* Scale comes from .brand so the logo tracks it. The vw term there is offset
     so the lockup keeps clear of the signal light on narrow phones — a plain
     percentage grows too fast at the low end and collides around 375-390px. */
  font-size: 1em;
  /* Optical, not geometric, centring. The gnome's area centroid sits 58.6% down
     its height (thin hat, heavy beard), so this lifts the cap-height midpoint
     off the baseline to meet that centroid — above where it was, but still
     weighed below true centre. In em, so it holds at every size. */
  transform: translateY(-0.048em);
  /* Light weights need air; tight tracking closes up thin strokes at display
     sizes. */
  font-weight: 300;
  letter-spacing: normal;
  line-height: 1;
  color: var(--text);
}

.wordmark span {
  /* Same blue as the gnome's hat. */
  color: var(--accent);
  font-weight: 200;
}

/* Taken out of the flex flow so its width can't push the brand lockup off
   true centre. */
.signal-light {
  position: absolute;
  right: 0;
  top: 50%;
  /* The extra em nudges it off the topbar's box centre and onto the wordmark's
     cap-height midpoint, which sits slightly lower because the logo overhangs
     the text at the top. In em so it holds as the header scales. */
  transform: translateY(calc(-50% + 0.027em));
  width: 1.25rem;
  height: 1.25rem;
  border-radius: 50%;
  background: var(--signal-off);
  box-shadow: inset 0 0 4px rgba(0, 0, 0, 0.5);
  /* Pulse colour lives here so the two layers below can both read it and the
     downbeat variant only has to override one custom property. */
  --pulse: 255, 255, 255;
}

/* The afterglow is a separate layer from the lamp so the lamp's own edge can
   stay hard. Blurring the element itself (a wide box-shadow on the dot) is
   what made the indicator read as fuzzy — the halo bled back over the rim. */
.signal-light::after {
  content: '';
  position: absolute;
  /* Overshoots the dot; the gradient, not the box, defines where it ends. */
  inset: -140%;
  border-radius: 50%;
  background: radial-gradient(
    closest-side,
    rgba(var(--pulse), 0.55) 0%,
    rgba(var(--pulse), 0.22) 38%,
    rgba(var(--pulse), 0) 72%
  );
  opacity: 0;
  pointer-events: none;
}

/* Instant attack, near-instant fall to the lit floor: the lamp itself snaps,
   which is what makes the beat land on the frame you expect. */
.signal-light.flashing {
  animation: lamp-strike 0.16s linear;
}

/* The glow outlives the lamp by ~3x. That lag is the analog part — phosphor
   decay, not a symmetric fade in and out. */
.signal-light.flashing::after {
  animation: afterglow 0.52s linear;
}

/* Downbeat: accent blue. Blue is darker than the off-beat white, so the
   hierarchy is carried by a wider, longer-lived halo rather than by
   brightness — otherwise the accented beat reads as the weaker of the two. */
.signal-light.flashing.strong {
  --pulse: var(--accent-rgb);
  animation-name: lamp-strike-strong;
}

.signal-light.flashing.strong::after {
  inset: -260%;
  animation-duration: 0.78s;
}

@keyframes lamp-strike {
  0% {
    background: #ffffff;
    box-shadow: inset 0 0 0 rgba(0, 0, 0, 0);
  }
  55% {
    background: #ffffff;
  }
  100% {
    background: var(--signal-off);
    box-shadow: inset 0 0 4px rgba(0, 0, 0, 0.5);
  }
}

@keyframes lamp-strike-strong {
  0% {
    background: var(--accent);
    box-shadow: inset 0 0 0 rgba(0, 0, 0, 0);
  }
  55% {
    background: var(--accent);
  }
  100% {
    background: var(--signal-off);
    box-shadow: inset 0 0 4px rgba(0, 0, 0, 0.5);
  }
}

/* Hand-shaped exponential tail: most of the energy is gone in the first
   fifth, then a long low smear. A plain ease-out reads as a soft blur. */
@keyframes afterglow {
  0% {
    opacity: 1;
    transform: scale(0.82);
  }
  8% {
    opacity: 0.92;
    transform: scale(1);
  }
  22% {
    opacity: 0.44;
  }
  45% {
    opacity: 0.17;
  }
  70% {
    opacity: 0.06;
  }
  100% {
    opacity: 0;
    transform: scale(1.08);
  }
}

/* Warm accent so it reads as its own control rather than another grey chip —
   it's the only thing up here that changes the feel of the click. */
.time-sig {
  /* The +1px absorbs the removed 1px border, so swapping it for the ring
     leaves the rendered size unchanged. */
  padding: calc(0.5rem + 1px) calc(1.5rem + 1px);
  border-radius: 999px;
  border: none;
  background: var(--warm-fill);
  color: var(--warm);
  font-size: 1.2rem;
  font-weight: 600;
  font-variant-numeric: tabular-nums;
  letter-spacing: 0.02em;
  cursor: pointer;
  box-shadow: var(--ring-warm);
  transition: background 0.12s ease-out, transform 0.12s ease-out;
}

.time-sig:active {
  background: var(--warm-press);
  transform: scale(0.96);
}

.tempo-controls {
  display: flex;
  align-items: center;
  gap: 1.5rem;
  /* The BPM label is out of flow, so reserve the space it visually occupies —
     otherwise the row's gap to the slider collapses to the label's overhang. */
  margin-bottom: 1.25rem;
}

.step-button {
  width: 3.25rem;
  height: 3.25rem;
  display: flex;
  align-items: center;
  justify-content: center;
  border-radius: 50%;
  border: none;
  background: var(--surface-raised);
  color: var(--text);
  font-size: 1.5rem;
  line-height: 1;
  cursor: pointer;
  box-shadow: var(--ring-accent);
  transition: background 0.12s ease-out, transform 0.12s ease-out;
}

.step-button:active {
  background: var(--surface-pressed);
  transform: scale(0.94);
}

/* Geometric strokes rather than text glyphs. A font's "+" sits on the maths
   axis and "−" on its own optical line, neither of which is the centre of the
   em box, so a text button can't centre them however the line-height is set.
   Here the crossing point is (12,12) in a square viewBox, so flex centring is
   exact. Sized in em so each button scales its own icon. */
.icon {
  display: block;
  width: 0.9em;
  height: 0.9em;
  fill: none;
  stroke: currentColor;
  stroke-width: 2.5;
  stroke-linecap: round;
}

/* Only the number participates in the row's height, so `align-items: center`
   lines the readout up with the step buttons instead of centring the
   number-plus-label stack and pushing the number high. */
.tempo-display {
  position: relative;
  min-width: 8.5rem;
  text-align: center;
}

.tempo-value {
  display: block;
  font-size: 4rem;
  font-weight: 600;
  line-height: 1;
  /* Proportional figures, deliberately: tabular pads the narrow `1` out to a
     full advance width, which opens a visible hole between the `1` and `2` of
     `120`. Layout stability comes from .tempo-display's min-width instead, so
     the step buttons stay put without paying for tabular's spacing. */
  font-variant-numeric: proportional-nums;
  letter-spacing: normal;
}

/* Hangs below the number's box rather than sitting in flow under it, so the
   label can't drag the number off the step buttons' centre line. */
.unit {
  position: absolute;
  top: 100%;
  left: 0;
  right: 0;
  margin-top: 0.35rem;
  font-size: 0.75rem;
  font-weight: 600;
  letter-spacing: 0.18em;
  text-indent: 0.18em;
  color: var(--text-faint);
}

.slider-row {
  display: flex;
  align-items: center;
  gap: 0.85rem;
  width: 100%;
  max-width: 20rem;
}

.slider-bound {
  font-size: 0.75rem;
  font-variant-numeric: tabular-nums;
  color: var(--text-faint);
  flex-shrink: 0;
}

.slider {
  flex: 1;
  min-width: 0;
  height: 2.5rem;
  margin: 0;
  background: transparent;
  cursor: pointer;
  -webkit-appearance: none;
  appearance: none;
}

.slider::-webkit-slider-runnable-track {
  height: 0.375rem;
  border-radius: 999px;
  background: linear-gradient(
    to right,
    var(--accent) var(--fill, 0%),
    var(--surface-raised) var(--fill, 0%)
  );
}

.slider::-webkit-slider-thumb {
  -webkit-appearance: none;
  appearance: none;
  width: 1.5rem;
  height: 1.5rem;
  /* Centres a 24px thumb on a 6px track. */
  margin-top: -0.5625rem;
  border: none;
  border-radius: 50%;
  background: #fff;
  box-shadow: 0 1px 4px rgba(0, 0, 0, 0.5);
}

.slider::-moz-range-track {
  height: 0.375rem;
  border-radius: 999px;
  background: var(--surface-raised);
}

.slider::-moz-range-progress {
  height: 0.375rem;
  border-radius: 999px;
  background: var(--accent);
}

.slider::-moz-range-thumb {
  width: 1.5rem;
  height: 1.5rem;
  border: none;
  border-radius: 50%;
  background: #fff;
  box-shadow: 0 1px 4px rgba(0, 0, 0, 0.5);
}

.mute-bars {
  width: 100%;
  max-width: 20rem;
  display: flex;
  flex-direction: column;
  gap: 0.9rem;
  padding: 1rem 1.25rem;
  border-radius: 1rem;
  border: 1px solid var(--border);
  background: var(--surface);
}

.mute-toggle {
  display: flex;
  align-items: center;
  justify-content: space-between;
  font-size: 0.95rem;
  color: var(--text);
  cursor: pointer;
}

.switch {
  position: relative;
  display: inline-block;
  width: 3rem;
  height: 1.75rem;
  border-radius: 1rem;
  background: var(--surface-raised);
  box-shadow: var(--ring);
  transition: background 0.15s ease-out;
}

.switch.on {
  background: var(--accent);
}

.switch input {
  position: absolute;
  inset: 0;
  margin: 0;
  opacity: 0;
  cursor: pointer;
}

.switch-thumb {
  position: absolute;
  top: 0.2rem;
  left: 0.2rem;
  width: 1.35rem;
  height: 1.35rem;
  border-radius: 50%;
  background: #eee;
  transition: transform 0.15s ease-out;
}

.switch.on .switch-thumb {
  transform: translateX(1.25rem);
}

.mute-steppers {
  display: flex;
  flex-direction: column;
  gap: 0.6rem;
  padding-top: 0.6rem;
  border-top: 1px solid var(--border);
}

.mute-stepper {
  display: flex;
  align-items: center;
  justify-content: space-between;
  font-size: 0.9rem;
  color: var(--text-muted);
}

.mute-stepper-label {
  flex-shrink: 0;
}

.mute-stepper-controls {
  display: flex;
  align-items: center;
  gap: 0.75rem;
}

.mute-stepper-value {
  /* min-width, not width: setBarsOn/Off clamp only at the bottom (Math.max(1,
     n)), so the value can reach three digits and must be able to grow rather
     than clip. */
  min-width: 2.2rem;
  text-align: center;
  font-size: 1.75rem;
  font-weight: 600;
  font-variant-numeric: tabular-nums;
  color: #fff;
  flex-shrink: 0;
}

.mini-button {
  position: relative;
  width: 2.25rem;
  height: 2.25rem;
  display: flex;
  align-items: center;
  justify-content: center;
  border-radius: 50%;
  border: none;
  background: var(--surface-raised);
  color: var(--text);
  font-size: 1rem;
  line-height: 1;
  cursor: pointer;
  flex-shrink: 0;
  box-shadow: var(--ring-accent);
  transition: background 0.12s ease-out, transform 0.12s ease-out;
}

/* Shrinking the control shouldn't shrink the target: this pads the hit area
   back out to 44px without changing anything visible. */
.mini-button::after {
  content: '';
  position: absolute;
  inset: -0.25rem;
}

.mini-button:active {
  background: var(--surface-pressed);
  transform: scale(0.94);
}

.play-button {
  width: 100%;
  max-width: 20rem;
  padding: 1rem 3rem;
  border-radius: 999px;
  border: none;
  background: var(--accent);
  color: #fff;
  font-size: 1.15rem;
  font-weight: 600;
  letter-spacing: 0.02em;
  cursor: pointer;
  box-shadow: var(--ring-on-fill), 0 6px 20px var(--accent-glow);
  transition: background 0.12s ease-out, transform 0.12s ease-out, box-shadow 0.12s ease-out;
}

.play-button:active {
  transform: scale(0.97);
}

.play-button.playing {
  background: var(--stop);
  box-shadow: var(--ring-on-fill), 0 6px 20px var(--stop-glow);
}

:focus-visible {
  outline: 2px solid var(--accent-strong);
  outline-offset: 3px;
}

/* Short viewports — small windows, landscape phones. Tighten the vertical
   rhythm so the column still fits once Mute Bars is expanded. */
@media (max-height: 485px) {
  .app {
    gap: 0.5rem;
    padding-top: max(2.25rem, calc(env(safe-area-inset-top) + 2rem));
    padding-bottom: max(1rem, env(safe-area-inset-bottom));
  }

  .tempo-controls {
    margin-bottom: 0.6rem;
  }

  .tempo-value {
    font-size: 3rem;
  }

  .step-button {
    width: 2.75rem;
    height: 2.75rem;
  }

  .mute-bars {
    padding: 0.75rem 1.25rem;
    gap: 0.6rem;
  }

  .play-button {
    padding: 0.7rem 3rem;
  }
}

/* Shorter still. This is a separate, lower breakpoint on purpose: hiding the
   wordmark buys almost no vertical space — the topbar is absolutely positioned
   and the logo sets its height either way — so it isn't what makes the column
   fit. It's about the header not dominating a screen this small, which only
   starts to bite well below the tightening breakpoint. */
@media (max-height: 400px) {
  .wordmark {
    display: none;
  }

  .topbar {
    justify-content: flex-start;
  }

  /* .topbar drives the logo size, so pin it rather than letting the width-based
     clamp pick a header-sized gnome for a screen with no room for one. */
  .topbar {
    font-size: 2rem;
  }
}

@media (prefers-reduced-motion: reduce) {
  .signal-light.flashing,
  .signal-light.flashing.strong,
  .signal-light.flashing::after,
  .signal-light.flashing.strong::after {
    animation-duration: 0.01ms;
  }

  /* Eyes open, permanently. */
  .logo {
    animation: none;
  }

  .step-button,
  .mini-button,
  .play-button,
  .time-sig,
  .switch,
  .switch-thumb {
    transition: none;
  }

  .time-sig:active,
  .step-button:active,
  .mini-button:active,
  .play-button:active {
    transform: none;
  }
}
</style>
