import Capacitor
import WebKit

// Capacitor only auto-registers plugins that come from installed npm
// packages (via capacitor.config.json's package list generated by `cap
// sync`). Local plugin classes we add directly to the app target, like
// AudioSessionPlugin, need to be registered manually here.
class MainViewController: CAPBridgeViewController {
    override func capacitorDidLoad() {
        bridge?.registerPluginInstance(AudioSessionPlugin())
    }

    // WKWebView's Web Audio implementation always initializes under the
    // "ambient" AVAudioSession category (which respects the hardware mute
    // switch), regardless of what the app itself has configured. Disabling
    // this restriction is what actually lets our .playback category stick.
    override func webViewConfiguration(for instanceConfiguration: InstanceConfiguration) -> WKWebViewConfiguration {
        let config = super.webViewConfiguration(for: instanceConfiguration)
        config.mediaTypesRequiringUserActionForPlayback = []
        config.allowsInlineMediaPlayback = true
        return config
    }
}
